// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcQ1tyNF3bXACw0wCpvd2jIWP9Rp_BzSg',
    appId: '1:366668542659:web:da18ad14611147df152876',
    messagingSenderId: '366668542659',
    projectId: 'animate-87fd5',
    authDomain: 'animate-87fd5.firebaseapp.com',
    storageBucket: 'animate-87fd5.firebasestorage.app',
    measurementId: 'G-SBWX910H9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAJIC9SgNcIViqj0L7YKoO99Qs4QSUx4w',
    appId: '1:366668542659:android:7ca2cc1fbdba49f1152876',
    messagingSenderId: '366668542659',
    projectId: 'animate-87fd5',
    storageBucket: 'animate-87fd5.firebasestorage.app',
  );
}
